# Generated by Django 5.0.6 on 2024-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=255)),
                ('PCat', models.CharField(max_length=255)),
                ('PPrice', models.IntegerField(max_length=255)),
                ('PDescription', models.CharField(max_length=255)),
                ('PImage', models.ImageField(default='null.jpg', upload_to='sample1')),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='CImage',
            field=models.ImageField(default='null.jpg', upload_to='sample'),
        ),
    ]
