# Generated by Django 5.0.6 on 2024-08-22 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_cartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('postcode', models.CharField(max_length=25)),
                ('checkoutcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.cartdata')),
                ('usercheckout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.reg')),
            ],
        ),
    ]
